"""
Canary Runner (G3)

Scheduled canary tests for continuous verification.
Runs tests on a schedule and alerts on failures.
"""

import asyncio
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Any, Callable, Awaitable
from uuid import UUID, uuid4

from envelope.verification.golden_set import GoldenSetRunner, GoldenSetResult


@dataclass
class CanaryConfig:
    """Configuration for canary runner."""
    interval_seconds: float = 300.0  # 5 minutes
    max_consecutive_failures: int = 3
    alert_on_failure: bool = True
    run_on_start: bool = True
    tags: list[str] = field(default_factory=list)


@dataclass
class CanaryAlert:
    """Alert generated by canary failures."""
    alert_id: UUID
    run_id: UUID
    message: str
    consecutive_failures: int
    severity: str  # warning, critical
    timestamp: datetime = field(default_factory=datetime.utcnow)
    details: dict[str, Any] = field(default_factory=dict)


AlertCallback = Callable[[CanaryAlert], Awaitable[None]]


class CanaryRunner:
    """
    Scheduled canary test runner.

    Runs golden set tests on a schedule and generates alerts
    on failures. Useful for continuous monitoring of model behavior.
    """

    def __init__(
        self,
        golden_runner: GoldenSetRunner,
        config: CanaryConfig | None = None,
    ):
        self._golden_runner = golden_runner
        self._config = config or CanaryConfig()
        self._running = False
        self._task: asyncio.Task | None = None
        self._consecutive_failures = 0
        self._history: list[GoldenSetResult] = []
        self._alerts: list[CanaryAlert] = []
        self._alert_callbacks: list[AlertCallback] = []
        self._last_run: datetime | None = None

    @property
    def config(self) -> CanaryConfig:
        return self._config

    @property
    def is_running(self) -> bool:
        return self._running

    @property
    def consecutive_failures(self) -> int:
        return self._consecutive_failures

    @property
    def last_run(self) -> datetime | None:
        return self._last_run

    def add_alert_callback(self, callback: AlertCallback) -> None:
        """Add callback for alerts."""
        self._alert_callbacks.append(callback)

    def remove_alert_callback(self, callback: AlertCallback) -> bool:
        """Remove alert callback."""
        try:
            self._alert_callbacks.remove(callback)
            return True
        except ValueError:
            return False

    async def start(self) -> None:
        """Start the canary runner."""
        if self._running:
            return

        self._running = True

        if self._config.run_on_start:
            await self._run_canary()

        self._task = asyncio.create_task(self._run_loop())

    async def stop(self) -> None:
        """Stop the canary runner."""
        self._running = False
        if self._task:
            self._task.cancel()
            try:
                await self._task
            except asyncio.CancelledError:
                pass
            self._task = None

    async def _run_loop(self) -> None:
        """Main run loop."""
        while self._running:
            await asyncio.sleep(self._config.interval_seconds)
            if self._running:
                await self._run_canary()

    async def _run_canary(self) -> GoldenSetResult:
        """Run canary tests and handle results."""
        result = await self._golden_runner.run_all(
            tags=self._config.tags if self._config.tags else None
        )

        self._last_run = datetime.utcnow()
        self._history.append(result)

        if result.success:
            self._consecutive_failures = 0
        else:
            self._consecutive_failures += 1

            if self._config.alert_on_failure:
                await self._generate_alert(result)

        return result

    async def _generate_alert(self, result: GoldenSetResult) -> None:
        """Generate an alert for a failure."""
        severity = "warning"
        if self._consecutive_failures >= self._config.max_consecutive_failures:
            severity = "critical"

        failed_tests = [
            e.test_id for e in result.executions if not e.passed
        ]

        alert = CanaryAlert(
            alert_id=uuid4(),
            run_id=result.run_id,
            message=f"Canary tests failed: {result.failed}/{result.total} tests failed",
            consecutive_failures=self._consecutive_failures,
            severity=severity,
            details={
                "failed_tests": failed_tests,
                "pass_rate": result.pass_rate,
            },
        )

        self._alerts.append(alert)

        # Invoke callbacks
        for callback in self._alert_callbacks:
            try:
                await callback(alert)
            except Exception:
                pass  # Don't let callback errors break the runner

    async def run_once(self) -> GoldenSetResult:
        """Run canary tests once (manual trigger)."""
        return await self._run_canary()

    def get_history(self, limit: int = 10) -> list[GoldenSetResult]:
        """Get recent run history."""
        return self._history[-limit:]

    def get_alerts(
        self,
        severity: str | None = None,
        limit: int = 50,
    ) -> list[CanaryAlert]:
        """Get recent alerts."""
        alerts = self._alerts

        if severity:
            alerts = [a for a in alerts if a.severity == severity]

        return alerts[-limit:]

    def clear_alerts(self) -> int:
        """Clear all alerts. Returns count cleared."""
        count = len(self._alerts)
        self._alerts.clear()
        return count

    def get_status(self) -> dict[str, Any]:
        """Get canary runner status."""
        return {
            "running": self._running,
            "consecutive_failures": self._consecutive_failures,
            "last_run": self._last_run.isoformat() if self._last_run else None,
            "total_runs": len(self._history),
            "total_alerts": len(self._alerts),
            "config": {
                "interval_seconds": self._config.interval_seconds,
                "max_consecutive_failures": self._config.max_consecutive_failures,
                "alert_on_failure": self._config.alert_on_failure,
                "tags": self._config.tags,
            },
        }

    def get_health(self) -> dict[str, Any]:
        """Get health status for monitoring."""
        recent_runs = self._history[-10:]
        if not recent_runs:
            return {
                "healthy": True,
                "message": "No runs yet",
                "pass_rate": None,
            }

        recent_pass_rate = sum(r.pass_rate for r in recent_runs) / len(recent_runs)
        healthy = (
            self._consecutive_failures < self._config.max_consecutive_failures
            and recent_pass_rate > 0.8
        )

        return {
            "healthy": healthy,
            "message": "OK" if healthy else f"Degraded: {self._consecutive_failures} consecutive failures",
            "pass_rate": recent_pass_rate,
            "consecutive_failures": self._consecutive_failures,
        }
